config/routes.rb
Rails.application.routes.draw do
  root 'matches#new'
  resources :ceos
  resources :matches

end

app/models/ceo.rb
class Ceo < ActiveRecord::Base
  validates :name, presence: true
  validates :company, presence: true
  
  def wins
    Match.where(winner: self.id).count
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  validates :one, presence: true 
  validates :two, presence: true
  validates :winner, presence: true

  def self.new_contest
    Ceo.all.limit(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ceos_controller.rb
class CeosController < ApplicationController
  before_action :set_ceo, only: [:show, :edit, :update, :destroy]

  # GET /ceos
  # GET /ceos.json
  def index
    @ceos = Ceo.all
  end

  # GET /ceos/1
  # GET /ceos/1.json
  def show
  end

  # GET /ceos/new
  def new
    @ceo = Ceo.new
  end

  # GET /ceos/1/edit
  def edit
  end

  # POST /ceos
  # POST /ceos.json
  def create
    @ceo = Ceo.new(ceo_params)

    respond_to do |format|
      if @ceo.save
        format.html { redirect_to @ceo, notice: 'Ceo was successfully created.' }
        format.json { render :show, status: :created, location: @ceo }
      else
        format.html { render :new }
        format.json { render json: @ceo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ceos/1
  # PATCH/PUT /ceos/1.json
  def update
    respond_to do |format|
      if @ceo.update(ceo_params)
        format.html { redirect_to @ceo, notice: 'Ceo was successfully updated.' }
        format.json { render :show, status: :ok, location: @ceo }
      else
        format.html { render :edit }
        format.json { render json: @ceo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ceos/1
  # DELETE /ceos/1.json
  def destroy
    @ceo.destroy
    respond_to do |format|
      format.html { redirect_to ceos_url, notice: 'Ceo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ceo
      @ceo = Ceo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ceo_params
      params.require(:ceo).permit(:name, :salary, :company, :company_revenue, :number_employees)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def new 
    @contestants = Match.new_contest
  end

  def create
    @match = Match.new(match_params)
    @match.save
    redirect_to new_match_url, notice: "CEO #{selected_ceo.name} appreciates your vote of confidence"
  end

  private
  def selected_ceo
    Ceo.find(params[:match][:winner])
  end

  def match_params
    params.require(:match).permit(:one, :two, :winner)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ceos_helper.rb
module CeosHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/ceos/_form.html.erb
<%= form_for(@ceo) do |f| %>
  <% if @ceo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ceo.errors.count, "error") %> prohibited this ceo from being saved:</h2>

      <ul>
      <% @ceo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :company_revenue %><br>
    <%= f.number_field :company_revenue %>
  </div>
  <div class="field">
    <%= f.label :number_employees %><br>
    <%= f.number_field :number_employees %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ceos/edit.html.erb
<h1>Editing ceo</h1>

<%= render 'form' %>

<%= link_to 'Show', @ceo %> |
<%= link_to 'Back', ceos_path %>

app/views/ceos/index.html.erb
<h1>Listing ceos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Salary</th>
      <th>Company</th>
      <th>Company revenue</th>
      <th>Number employees</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ceos.each do |ceo| %>
      <tr>
        <td><%= ceo.name %></td>
        <td><%= ceo.salary %></td>
        <td><%= ceo.company %></td>
        <td><%= ceo.company_revenue %></td>
        <td><%= ceo.number_employees %></td>
        <td><%= link_to 'Show', ceo %></td>
        <td><%= link_to 'Edit', edit_ceo_path(ceo) %></td>
        <td><%= link_to 'Destroy', ceo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ceo', new_ceo_path %>

app/views/ceos/new.html.erb
<h1>New ceo</h1>

<%= render 'form' %>

<%= link_to 'Back', ceos_path %>

app/views/ceos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ceo.name %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @ceo.salary %>
</p>

<p>
  <strong>Company:</strong>
  <%= @ceo.company %>
</p>

<p>
  <strong>Company revenue:</strong>
  <%= @ceo.company_revenue %>
</p>

<p>
  <strong>Number employees:</strong>
  <%= @ceo.number_employees %>
</p>

<%= link_to 'Edit', edit_ceo_path(@ceo) %> |
<%= link_to 'Back', ceos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CeoCageMatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/matches/new.html.haml
%h1 Matches#new
- @contestants.each do |contestant|
  %p= "CEO Name: #{contestant.name}"
  %p= "Company:  #{contestant.company}"
  %button{id: ['contestant', contestant.id]} Like

app/views/matches/show.html.haml
%h1 Matches#show
- @contestants.each do |contestant|
  %p= "CEO Name: #{contestant.name}"
  %p= "Company:  #{contestant.company}"
  %button{id: ['contestant', contestant.id]} Like